- name: Run Docker Container
  hosts: 127.0.0.1
  connection: local
  become: false
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:

    - name: log into docker hub registry
      docker_login:
        username: "{{username}}"
        password: "{{password}}"
      docker_image:
        source: pull
        name: triforceadi/minimal-courier-api:latest

    - name: Run Docker Container
      docker_container:
        name: local_container
        image: triforceadi/minimal-courier-api:latest
        state: started
        ports:
          - "3000:3000"